- name: Cria usuario
  hosts: nextcloud
  become: yes

  tasks:
    - name: Adiciona usuário do Nextcloud via docker exec
      script: ./scripts/add-user.sh {{ display_name }} {{ email }}
      register: add_user_output

    - name: Show output from user addition
      debug:
        var: add_user_output.stdout

