- name: Define quota para usuário
  hosts: nextcloud
  become: yes
  tasks:
    - name: Define quota para usuário do Nextcloud via docker exec
      script: ./scripts/set-group-quota.sh {{ email }} {{ quota }}GB
      register: set_quota_output

    - name: Quota output
      debug:
        var: set_quota_output.stdout

